/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_spring_mybatis_java_study;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
